#!/bin/bash

# (To have the exact names of these devices you should type the command : xsetwacom --list devices )
stylus="Wacom Serial Penabled 1FG Touchscreen stylus" 
eraser="Wacom Serial Penabled 1FG Touchscreen eraser"

function rotate {
    if [ $# -lt 1  ]; then  # error ...
	exit 1 
    fi

    case "$1" in
        up)
            nextRotate="none"
            nextOrient="normal" ;;
        down)
            nextRotate="half"
            nextOrient="inverted" ;;
	right)
            nextRotate="ccw"
            nextOrient="left" ;;
	left)
            nextRotate="cw"
            nextOrient="right";;
    esac

    # Rotate the screen      
    xrandr -o $nextOrient

    # Rotate the tablet                      
    xsetwacom set "$stylus" Rotate $nextRotate
    xsetwacom set "$eraser" Rotate $nextRotate

}

while true; do
    # 1) We extract data about the actual position
    position=$(cat /sys/devices/platform/hdaps/position)
    x=$(echo $position | sed -n "s/(\([-0-9]*\),\([-0-9]*\).*)/\1/p") # most of time contained in [350,650]
    y=$(echo $position | sed -n "s/(\([-0-9]*\),\([-0-9]*\).*)/\2/p") # most of time contained in [-650,-350]

    # 2) We work out the x value (= left and right inclination) (always between 
    if [ $x -lt 400  ]; then
	rotate left
    elif [ $x -gt 600  ]; then
	rotate right
    fi
    
    # 3) We work out the y value (= front and back inclination)
    if [ $y -gt -400  ]; then
	rotate down
    elif [ $y -lt -600  ]; then
	rotate up
    fi

    # 4) wait before checking the value again
    sleep 0.5
done

