#!/usr/bin/env sh

# set preferred screens layout
xrandr --output VGA1 --auto --left-of LVDS1
xrandr --output VGA1 --rotate left
xrandr --output VGA1 --primary
xrandr --output LVDS1 --auto --pos 1080x1152
# prevent screen from blanking
export DISPLAY=:0.0
xset s off
xset s noblank
xset -dpms

# start skype
skype &

# change keymap to Polish
setxkbmap pl

# Disable the touchpad
xinput set-prop "SynPS/2 Synaptics TouchPad" "Device Enabled" 0

# Restore wallpaper
nitrogen --restore
